# Generated by Django 5.1.1 on 2024-10-04 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0003_alter_bookdata_short_story"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookdata",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="bookdata",
            name="isbn",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="ISBN"
            ),
        ),
    ]
