# Generated by Django 5.1.1 on 2024-10-16 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0005_alter_bookdata_options_bookdata_thumbnail_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookdata",
            name="page",
            field=models.IntegerField(
                blank=True, max_length=100, null=True, verbose_name="ページ数"
            ),
        ),
    ]
