# Generated by Django 5.1.1 on 2024-10-03 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "award_winning",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="受賞回"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="タイトル"
                    ),
                ),
                (
                    "author",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="著者"
                    ),
                ),
                (
                    "publisher",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="出版社"
                    ),
                ),
                (
                    "release_date",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="発売日"
                    ),
                ),
                (
                    "isbn",
                    models.CharField(
                        blank=True, max_length=13, null=True, verbose_name="ISBN"
                    ),
                ),
                (
                    "page",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="ページ数"
                    ),
                ),
                (
                    "summary",
                    models.TextField(blank=True, null=True, verbose_name="あらすじ"),
                ),
                (
                    "url",
                    models.TextField(blank=True, null=True, verbose_name="AmazonURL"),
                ),
                (
                    "genre1",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="ジャンル1"
                    ),
                ),
                (
                    "genre2",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="ジャンル2"
                    ),
                ),
                (
                    "short_story",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="短編"
                    ),
                ),
                (
                    "year_awarded",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="受賞年"
                    ),
                ),
                (
                    "cust_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="ID"
                    ),
                ),
            ],
            options={
                "verbose_name": "直木賞の書籍",
                "verbose_name_plural": "直木賞書籍リスト",
                "db_table": "book_data",
            },
        ),
        migrations.DeleteModel(name="SampleModel",),
    ]
