# Generated by Django 5.1.1 on 2024-10-03 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0002_bookdata_delete_samplemodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookdata",
            name="short_story",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="短編集か"
            ),
        ),
    ]
