# Generated by Django 5.1.1 on 2024-10-09 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0004_alter_bookdata_id_alter_bookdata_isbn"),
    ]

    operations = [
        migrations.AlterModelOptions(name="bookdata", options={},),
        migrations.AddField(
            model_name="bookdata",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="book_thumbnails/"
            ),
        ),
        migrations.AlterModelTable(name="bookdata", table=None,),
    ]
